// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wprawka1.Data;

#nullable disable

namespace Wprawka1.Migrations
{
    [DbContext(typeof(Biblioteka))]
    [Migration("20260322130914_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wprawka1.Models.Czytelnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KartaBiblioteczna")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Czytelnicy");
                });

            modelBuilder.Entity("Wprawka1.Models.Ksiazka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IDwydawcy")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("wydawcaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("wydawcaId");

                    b.ToTable("Ksiazki");
                });

            modelBuilder.Entity("Wprawka1.Models.Wydawca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Wydawcy");
                });

            modelBuilder.Entity("Wprawka1.Models.Wypozyczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataWypozyczenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZwrotu")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDczytelnika")
                        .HasColumnType("int");

                    b.Property<int>("IDksiazki")
                        .HasColumnType("int");

                    b.Property<int>("czytelnikId")
                        .HasColumnType("int");

                    b.Property<int>("ksiazkaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("czytelnikId");

                    b.HasIndex("ksiazkaId");

                    b.ToTable("Wypozyczenia");
                });

            modelBuilder.Entity("Wprawka1.Models.Ksiazka", b =>
                {
                    b.HasOne("Wprawka1.Models.Wydawca", "wydawca")
                        .WithMany("Ksiazki")
                        .HasForeignKey("wydawcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("wydawca");
                });

            modelBuilder.Entity("Wprawka1.Models.Wypozyczenie", b =>
                {
                    b.HasOne("Wprawka1.Models.Czytelnik", "czytelnik")
                        .WithMany("Wypozyczenia")
                        .HasForeignKey("czytelnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wprawka1.Models.Ksiazka", "ksiazka")
                        .WithMany("Wypozyczania")
                        .HasForeignKey("ksiazkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("czytelnik");

                    b.Navigation("ksiazka");
                });

            modelBuilder.Entity("Wprawka1.Models.Czytelnik", b =>
                {
                    b.Navigation("Wypozyczenia");
                });

            modelBuilder.Entity("Wprawka1.Models.Ksiazka", b =>
                {
                    b.Navigation("Wypozyczania");
                });

            modelBuilder.Entity("Wprawka1.Models.Wydawca", b =>
                {
                    b.Navigation("Ksiazki");
                });
#pragma warning restore 612, 618
        }
    }
}
